### ISSUE TITLE
i can't even do yarn add imagesearch

### ISSUE THREAD

**Issue by hiwyn** [monai/node-imagesearch#7]
when i try: `yarn add imagesearch`

thats are the results on terminal:
https://pastebin.com/ZNWAYFfE

what should i do?

**Comment by monai** [comment]
Well, you have two options: don't use it or fork and update native bindings to the current Node.js version.

**Comment by hiwyn** [comment]
how to do this update?
i've found `nvm` on the internet, it can be used to use a old node.js version to make it work?
which version should i use?
